from champInterpreter.imageCapture import captureNames
from champInterpreter.imageToString import convertImagetoString
from champInterpreter.champDatabaseManager import connect
from champInterpreter.champDatabaseManager import getChampion
from champInterpreter.findChampion import getChampionNames